services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
            - NODE_ENV=production
        restart: always
        container_name: website-example-server-1
