services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
        restart: always
        container_name: website-example-server-1
